name: happy_dog_house
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  advertising_id: ^2.7.1
  flutter_svg: ^2.0.17
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/

  fonts:
      - family: Bur
        fonts:
          - asset: assets/fonts/One.ttf

